# Generated by Django 4.1 on 2023-04-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_restaurant_img1_url_restaurant_img2_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='img1_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='img2_url',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='img3_url',
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='No image available', max_length=300, null=True)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.restaurant')),
            ],
        ),
    ]
